CREATE TABLE UserSettings (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    theme BOOLEAN DEFAULT FALSE,
    notification BOOLEAN DEFAULT TRUE,
    appLanguage VARCHAR(255) DEFAULT 'ENG',
    user_id BIGINT NOT NULL UNIQUE,
    FOREIGN KEY (user_id) REFERENCES User(id) ON DELETE CASCADE
);
